//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/InputAction/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""30f5ead3-d948-4c6d-a7d5-67b9001585ec"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""e8fd8ff2-65d7-44d1-8dae-01ddf3c23cc4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""afc3e2e1-9edb-4d43-b592-c13e64b52a07"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""PassThrough"",
                    ""id"": ""13228eee-aea2-4664-8fbf-d24f1f07c0c0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TempItemUse"",
                    ""type"": ""Button"",
                    ""id"": ""1fe494bc-c607-4f40-b727-3b417af9237b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TakeItem"",
                    ""type"": ""Button"",
                    ""id"": ""fc9000cd-ddca-42b9-84d0-31df0c7d8b77"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestMakeItem"",
                    ""type"": ""Button"",
                    ""id"": ""76518a53-7e29-4ad4-b675-a9a25734c8e4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""4781acbb-145a-4f01-aa7c-2903d649b8d1"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b8155a9e-bfa7-43e4-b4c8-12b768e85415"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e8935b68-feec-46fe-a9ef-e90d81559a9c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""095d0fa3-a748-4746-9680-4cb4baba4f89"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""62c1889e-9789-40f6-b056-64d34a8fbf37"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Player"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8a847583-bf92-4a71-84fb-4206519513da"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5a9feb9-b280-41d5-b699-fddc6762a19a"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1004cfaf-fd86-4848-920d-cf193e3fa389"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TempItemUse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2dda013b-bc44-4459-b3d9-70eef89b8e3e"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae2f8c73-ea97-4947-81cc-5c3c090d5440"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestMakeItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""InventoryUI"",
            ""id"": ""c6136a03-b10e-4638-8431-feefc00506e7"",
            ""actions"": [
                {
                    ""name"": ""InventoryOnOff"",
                    ""type"": ""Button"",
                    ""id"": ""1025edbf-0a0a-4aea-b6ee-e78012e6359d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryItemUse"",
                    ""type"": ""Button"",
                    ""id"": ""bb1cb9c1-712e-42b3-be28-f9c537c3dfbb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8287b1d8-19c6-45d2-aad6-efe8642a520c"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryOnOff"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db3e1b6a-d0e6-461f-8b5e-ff8b1b83d184"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryItemUse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""StoreUI"",
            ""id"": ""92bd2df5-bd75-4932-91e0-c5007a57a749"",
            ""actions"": [
                {
                    ""name"": ""StoreUIOnOff"",
                    ""type"": ""Button"",
                    ""id"": ""7a3a8894-95a6-4758-b9b3-6901ea593871"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a409d15d-5f93-4633-94bb-c905b8d57ec3"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StoreUIOnOff"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""EquipmentUI"",
            ""id"": ""8f3042f4-179a-485c-ab60-517739098c4f"",
            ""actions"": [
                {
                    ""name"": ""EquipmentOnOff"",
                    ""type"": ""Button"",
                    ""id"": ""90c77fbd-3e62-4037-bb61-6aae4efb806f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EquipmentItemUse"",
                    ""type"": ""Button"",
                    ""id"": ""a6c252da-fad2-4e39-837d-6472b52dafeb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9b5495a3-07cb-4a85-88d1-fd25a38b3ceb"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EquipmentOnOff"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c910ba6a-7769-45c7-bbe0-8f1bb097094a"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EquipmentItemUse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""SkillUI"",
            ""id"": ""460549ee-e10f-4b0b-9a55-f5ac34724e92"",
            ""actions"": [
                {
                    ""name"": ""SkillWindowOnOff"",
                    ""type"": ""Button"",
                    ""id"": ""c6b9f93c-d559-4988-a57a-913cb3f4ef73"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""97428b72-9de3-4903-a221-c348819d8595"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillWindowOnOff"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""QuickSlotUI"",
            ""id"": ""f6220187-1fcb-4bb7-b43a-e7dff5ce13d3"",
            ""actions"": [
                {
                    ""name"": ""QuickSlot1"",
                    ""type"": ""Button"",
                    ""id"": ""1d55a9eb-d6cd-49f7-a94b-07e2c60c477a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QuickSlot2"",
                    ""type"": ""Button"",
                    ""id"": ""272ca279-bdf9-4017-bbd8-a1a68aa5be54"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QuickSlot3"",
                    ""type"": ""Button"",
                    ""id"": ""473590b7-c3c1-4c27-8b03-bd128d834821"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QuickSlot4"",
                    ""type"": ""Button"",
                    ""id"": ""469a99ed-cff4-4ce4-b796-12ffe19ee014"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QuickSlot5"",
                    ""type"": ""Button"",
                    ""id"": ""bfa78ab4-3b7e-4fbc-b3aa-e89230b1ad19"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QuickSlot6"",
                    ""type"": ""Button"",
                    ""id"": ""f3c09683-931c-475c-9cac-d80b2ee96ff1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7edaffad-722a-4d7d-9d94-5634c4a2b13e"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuickSlot1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07df50b0-65d4-46b3-a6af-936bb42ccaa0"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuickSlot2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f057ac4d-547f-445f-99a0-55c41f59419f"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuickSlot3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51be3d02-b709-4a7e-9564-4a4313b54c27"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuickSlot4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1e4c469-7c17-4541-8b37-48cd4ac7aeda"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuickSlot5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5407554b-63b3-4a82-877c-ec03292094a3"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuickSlot6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MainMenuUI"",
            ""id"": ""40214cc4-be9c-40eb-a560-22336753277d"",
            ""actions"": [
                {
                    ""name"": ""StartMainMenu"",
                    ""type"": ""Button"",
                    ""id"": ""9e79fb37-3dd8-4144-855f-72d09af10623"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""85f831a9-f3cc-4409-891b-8fce083981de"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartMainMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Skill_Implement"",
            ""id"": ""407eb8de-d385-4065-84e9-9d45502adfaf"",
            ""actions"": [
                {
                    ""name"": ""FindingTarget"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d2ae6756-01c2-4923-a06c-d0b5ec85a6fb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ClickTarget"",
                    ""type"": ""PassThrough"",
                    ""id"": ""acb2f213-0fcb-4a52-8403-39a8eb0fa759"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""54c3593b-a08b-4e81-8ce7-7e2ba57d1872"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FindingTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""161e0e57-1198-4129-a26d-94de4b3e2f19"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClickTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""LoadingUI"",
            ""id"": ""e0cff282-5258-4d1a-bbc4-34b4d7e9ca81"",
            ""actions"": [
                {
                    ""name"": ""GoToNextScene"",
                    ""type"": ""Button"",
                    ""id"": ""ff951f02-f7c3-4dc3-b7d9-3552cee1b795"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9419bc7e-1244-42f8-8b1c-c57af5aa9b42"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GoToNextScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Player"",
            ""bindingGroup"": ""Player"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Attack = m_Player.FindAction("Attack", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_TempItemUse = m_Player.FindAction("TempItemUse", throwIfNotFound: true);
        m_Player_TakeItem = m_Player.FindAction("TakeItem", throwIfNotFound: true);
        m_Player_TestMakeItem = m_Player.FindAction("TestMakeItem", throwIfNotFound: true);
        // InventoryUI
        m_InventoryUI = asset.FindActionMap("InventoryUI", throwIfNotFound: true);
        m_InventoryUI_InventoryOnOff = m_InventoryUI.FindAction("InventoryOnOff", throwIfNotFound: true);
        m_InventoryUI_InventoryItemUse = m_InventoryUI.FindAction("InventoryItemUse", throwIfNotFound: true);
        // StoreUI
        m_StoreUI = asset.FindActionMap("StoreUI", throwIfNotFound: true);
        m_StoreUI_StoreUIOnOff = m_StoreUI.FindAction("StoreUIOnOff", throwIfNotFound: true);
        // EquipmentUI
        m_EquipmentUI = asset.FindActionMap("EquipmentUI", throwIfNotFound: true);
        m_EquipmentUI_EquipmentOnOff = m_EquipmentUI.FindAction("EquipmentOnOff", throwIfNotFound: true);
        m_EquipmentUI_EquipmentItemUse = m_EquipmentUI.FindAction("EquipmentItemUse", throwIfNotFound: true);
        // SkillUI
        m_SkillUI = asset.FindActionMap("SkillUI", throwIfNotFound: true);
        m_SkillUI_SkillWindowOnOff = m_SkillUI.FindAction("SkillWindowOnOff", throwIfNotFound: true);
        // QuickSlotUI
        m_QuickSlotUI = asset.FindActionMap("QuickSlotUI", throwIfNotFound: true);
        m_QuickSlotUI_QuickSlot1 = m_QuickSlotUI.FindAction("QuickSlot1", throwIfNotFound: true);
        m_QuickSlotUI_QuickSlot2 = m_QuickSlotUI.FindAction("QuickSlot2", throwIfNotFound: true);
        m_QuickSlotUI_QuickSlot3 = m_QuickSlotUI.FindAction("QuickSlot3", throwIfNotFound: true);
        m_QuickSlotUI_QuickSlot4 = m_QuickSlotUI.FindAction("QuickSlot4", throwIfNotFound: true);
        m_QuickSlotUI_QuickSlot5 = m_QuickSlotUI.FindAction("QuickSlot5", throwIfNotFound: true);
        m_QuickSlotUI_QuickSlot6 = m_QuickSlotUI.FindAction("QuickSlot6", throwIfNotFound: true);
        // MainMenuUI
        m_MainMenuUI = asset.FindActionMap("MainMenuUI", throwIfNotFound: true);
        m_MainMenuUI_StartMainMenu = m_MainMenuUI.FindAction("StartMainMenu", throwIfNotFound: true);
        // Skill_Implement
        m_Skill_Implement = asset.FindActionMap("Skill_Implement", throwIfNotFound: true);
        m_Skill_Implement_FindingTarget = m_Skill_Implement.FindAction("FindingTarget", throwIfNotFound: true);
        m_Skill_Implement_ClickTarget = m_Skill_Implement.FindAction("ClickTarget", throwIfNotFound: true);
        // LoadingUI
        m_LoadingUI = asset.FindActionMap("LoadingUI", throwIfNotFound: true);
        m_LoadingUI_GoToNextScene = m_LoadingUI.FindAction("GoToNextScene", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Attack;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_TempItemUse;
    private readonly InputAction m_Player_TakeItem;
    private readonly InputAction m_Player_TestMakeItem;
    public struct PlayerActions
    {
        private @PlayerInput m_Wrapper;
        public PlayerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Attack => m_Wrapper.m_Player_Attack;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @TempItemUse => m_Wrapper.m_Player_TempItemUse;
        public InputAction @TakeItem => m_Wrapper.m_Player_TakeItem;
        public InputAction @TestMakeItem => m_Wrapper.m_Player_TestMakeItem;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Attack.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack;
                @Look.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @TempItemUse.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTempItemUse;
                @TempItemUse.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTempItemUse;
                @TempItemUse.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTempItemUse;
                @TakeItem.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTakeItem;
                @TakeItem.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTakeItem;
                @TakeItem.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTakeItem;
                @TestMakeItem.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTestMakeItem;
                @TestMakeItem.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTestMakeItem;
                @TestMakeItem.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTestMakeItem;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @TempItemUse.started += instance.OnTempItemUse;
                @TempItemUse.performed += instance.OnTempItemUse;
                @TempItemUse.canceled += instance.OnTempItemUse;
                @TakeItem.started += instance.OnTakeItem;
                @TakeItem.performed += instance.OnTakeItem;
                @TakeItem.canceled += instance.OnTakeItem;
                @TestMakeItem.started += instance.OnTestMakeItem;
                @TestMakeItem.performed += instance.OnTestMakeItem;
                @TestMakeItem.canceled += instance.OnTestMakeItem;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // InventoryUI
    private readonly InputActionMap m_InventoryUI;
    private IInventoryUIActions m_InventoryUIActionsCallbackInterface;
    private readonly InputAction m_InventoryUI_InventoryOnOff;
    private readonly InputAction m_InventoryUI_InventoryItemUse;
    public struct InventoryUIActions
    {
        private @PlayerInput m_Wrapper;
        public InventoryUIActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @InventoryOnOff => m_Wrapper.m_InventoryUI_InventoryOnOff;
        public InputAction @InventoryItemUse => m_Wrapper.m_InventoryUI_InventoryItemUse;
        public InputActionMap Get() { return m_Wrapper.m_InventoryUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InventoryUIActions set) { return set.Get(); }
        public void SetCallbacks(IInventoryUIActions instance)
        {
            if (m_Wrapper.m_InventoryUIActionsCallbackInterface != null)
            {
                @InventoryOnOff.started -= m_Wrapper.m_InventoryUIActionsCallbackInterface.OnInventoryOnOff;
                @InventoryOnOff.performed -= m_Wrapper.m_InventoryUIActionsCallbackInterface.OnInventoryOnOff;
                @InventoryOnOff.canceled -= m_Wrapper.m_InventoryUIActionsCallbackInterface.OnInventoryOnOff;
                @InventoryItemUse.started -= m_Wrapper.m_InventoryUIActionsCallbackInterface.OnInventoryItemUse;
                @InventoryItemUse.performed -= m_Wrapper.m_InventoryUIActionsCallbackInterface.OnInventoryItemUse;
                @InventoryItemUse.canceled -= m_Wrapper.m_InventoryUIActionsCallbackInterface.OnInventoryItemUse;
            }
            m_Wrapper.m_InventoryUIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @InventoryOnOff.started += instance.OnInventoryOnOff;
                @InventoryOnOff.performed += instance.OnInventoryOnOff;
                @InventoryOnOff.canceled += instance.OnInventoryOnOff;
                @InventoryItemUse.started += instance.OnInventoryItemUse;
                @InventoryItemUse.performed += instance.OnInventoryItemUse;
                @InventoryItemUse.canceled += instance.OnInventoryItemUse;
            }
        }
    }
    public InventoryUIActions @InventoryUI => new InventoryUIActions(this);

    // StoreUI
    private readonly InputActionMap m_StoreUI;
    private IStoreUIActions m_StoreUIActionsCallbackInterface;
    private readonly InputAction m_StoreUI_StoreUIOnOff;
    public struct StoreUIActions
    {
        private @PlayerInput m_Wrapper;
        public StoreUIActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @StoreUIOnOff => m_Wrapper.m_StoreUI_StoreUIOnOff;
        public InputActionMap Get() { return m_Wrapper.m_StoreUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(StoreUIActions set) { return set.Get(); }
        public void SetCallbacks(IStoreUIActions instance)
        {
            if (m_Wrapper.m_StoreUIActionsCallbackInterface != null)
            {
                @StoreUIOnOff.started -= m_Wrapper.m_StoreUIActionsCallbackInterface.OnStoreUIOnOff;
                @StoreUIOnOff.performed -= m_Wrapper.m_StoreUIActionsCallbackInterface.OnStoreUIOnOff;
                @StoreUIOnOff.canceled -= m_Wrapper.m_StoreUIActionsCallbackInterface.OnStoreUIOnOff;
            }
            m_Wrapper.m_StoreUIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @StoreUIOnOff.started += instance.OnStoreUIOnOff;
                @StoreUIOnOff.performed += instance.OnStoreUIOnOff;
                @StoreUIOnOff.canceled += instance.OnStoreUIOnOff;
            }
        }
    }
    public StoreUIActions @StoreUI => new StoreUIActions(this);

    // EquipmentUI
    private readonly InputActionMap m_EquipmentUI;
    private IEquipmentUIActions m_EquipmentUIActionsCallbackInterface;
    private readonly InputAction m_EquipmentUI_EquipmentOnOff;
    private readonly InputAction m_EquipmentUI_EquipmentItemUse;
    public struct EquipmentUIActions
    {
        private @PlayerInput m_Wrapper;
        public EquipmentUIActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @EquipmentOnOff => m_Wrapper.m_EquipmentUI_EquipmentOnOff;
        public InputAction @EquipmentItemUse => m_Wrapper.m_EquipmentUI_EquipmentItemUse;
        public InputActionMap Get() { return m_Wrapper.m_EquipmentUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EquipmentUIActions set) { return set.Get(); }
        public void SetCallbacks(IEquipmentUIActions instance)
        {
            if (m_Wrapper.m_EquipmentUIActionsCallbackInterface != null)
            {
                @EquipmentOnOff.started -= m_Wrapper.m_EquipmentUIActionsCallbackInterface.OnEquipmentOnOff;
                @EquipmentOnOff.performed -= m_Wrapper.m_EquipmentUIActionsCallbackInterface.OnEquipmentOnOff;
                @EquipmentOnOff.canceled -= m_Wrapper.m_EquipmentUIActionsCallbackInterface.OnEquipmentOnOff;
                @EquipmentItemUse.started -= m_Wrapper.m_EquipmentUIActionsCallbackInterface.OnEquipmentItemUse;
                @EquipmentItemUse.performed -= m_Wrapper.m_EquipmentUIActionsCallbackInterface.OnEquipmentItemUse;
                @EquipmentItemUse.canceled -= m_Wrapper.m_EquipmentUIActionsCallbackInterface.OnEquipmentItemUse;
            }
            m_Wrapper.m_EquipmentUIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @EquipmentOnOff.started += instance.OnEquipmentOnOff;
                @EquipmentOnOff.performed += instance.OnEquipmentOnOff;
                @EquipmentOnOff.canceled += instance.OnEquipmentOnOff;
                @EquipmentItemUse.started += instance.OnEquipmentItemUse;
                @EquipmentItemUse.performed += instance.OnEquipmentItemUse;
                @EquipmentItemUse.canceled += instance.OnEquipmentItemUse;
            }
        }
    }
    public EquipmentUIActions @EquipmentUI => new EquipmentUIActions(this);

    // SkillUI
    private readonly InputActionMap m_SkillUI;
    private ISkillUIActions m_SkillUIActionsCallbackInterface;
    private readonly InputAction m_SkillUI_SkillWindowOnOff;
    public struct SkillUIActions
    {
        private @PlayerInput m_Wrapper;
        public SkillUIActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @SkillWindowOnOff => m_Wrapper.m_SkillUI_SkillWindowOnOff;
        public InputActionMap Get() { return m_Wrapper.m_SkillUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SkillUIActions set) { return set.Get(); }
        public void SetCallbacks(ISkillUIActions instance)
        {
            if (m_Wrapper.m_SkillUIActionsCallbackInterface != null)
            {
                @SkillWindowOnOff.started -= m_Wrapper.m_SkillUIActionsCallbackInterface.OnSkillWindowOnOff;
                @SkillWindowOnOff.performed -= m_Wrapper.m_SkillUIActionsCallbackInterface.OnSkillWindowOnOff;
                @SkillWindowOnOff.canceled -= m_Wrapper.m_SkillUIActionsCallbackInterface.OnSkillWindowOnOff;
            }
            m_Wrapper.m_SkillUIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SkillWindowOnOff.started += instance.OnSkillWindowOnOff;
                @SkillWindowOnOff.performed += instance.OnSkillWindowOnOff;
                @SkillWindowOnOff.canceled += instance.OnSkillWindowOnOff;
            }
        }
    }
    public SkillUIActions @SkillUI => new SkillUIActions(this);

    // QuickSlotUI
    private readonly InputActionMap m_QuickSlotUI;
    private IQuickSlotUIActions m_QuickSlotUIActionsCallbackInterface;
    private readonly InputAction m_QuickSlotUI_QuickSlot1;
    private readonly InputAction m_QuickSlotUI_QuickSlot2;
    private readonly InputAction m_QuickSlotUI_QuickSlot3;
    private readonly InputAction m_QuickSlotUI_QuickSlot4;
    private readonly InputAction m_QuickSlotUI_QuickSlot5;
    private readonly InputAction m_QuickSlotUI_QuickSlot6;
    public struct QuickSlotUIActions
    {
        private @PlayerInput m_Wrapper;
        public QuickSlotUIActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @QuickSlot1 => m_Wrapper.m_QuickSlotUI_QuickSlot1;
        public InputAction @QuickSlot2 => m_Wrapper.m_QuickSlotUI_QuickSlot2;
        public InputAction @QuickSlot3 => m_Wrapper.m_QuickSlotUI_QuickSlot3;
        public InputAction @QuickSlot4 => m_Wrapper.m_QuickSlotUI_QuickSlot4;
        public InputAction @QuickSlot5 => m_Wrapper.m_QuickSlotUI_QuickSlot5;
        public InputAction @QuickSlot6 => m_Wrapper.m_QuickSlotUI_QuickSlot6;
        public InputActionMap Get() { return m_Wrapper.m_QuickSlotUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(QuickSlotUIActions set) { return set.Get(); }
        public void SetCallbacks(IQuickSlotUIActions instance)
        {
            if (m_Wrapper.m_QuickSlotUIActionsCallbackInterface != null)
            {
                @QuickSlot1.started -= m_Wrapper.m_QuickSlotUIActionsCallbackInterface.OnQuickSlot1;
                @QuickSlot1.performed -= m_Wrapper.m_QuickSlotUIActionsCallbackInterface.OnQuickSlot1;
                @QuickSlot1.canceled -= m_Wrapper.m_QuickSlotUIActionsCallbackInterface.OnQuickSlot1;
                @QuickSlot2.started -= m_Wrapper.m_QuickSlotUIActionsCallbackInterface.OnQuickSlot2;
                @QuickSlot2.performed -= m_Wrapper.m_QuickSlotUIActionsCallbackInterface.OnQuickSlot2;
                @QuickSlot2.canceled -= m_Wrapper.m_QuickSlotUIActionsCallbackInterface.OnQuickSlot2;
                @QuickSlot3.started -= m_Wrapper.m_QuickSlotUIActionsCallbackInterface.OnQuickSlot3;
                @QuickSlot3.performed -= m_Wrapper.m_QuickSlotUIActionsCallbackInterface.OnQuickSlot3;
                @QuickSlot3.canceled -= m_Wrapper.m_QuickSlotUIActionsCallbackInterface.OnQuickSlot3;
                @QuickSlot4.started -= m_Wrapper.m_QuickSlotUIActionsCallbackInterface.OnQuickSlot4;
                @QuickSlot4.performed -= m_Wrapper.m_QuickSlotUIActionsCallbackInterface.OnQuickSlot4;
                @QuickSlot4.canceled -= m_Wrapper.m_QuickSlotUIActionsCallbackInterface.OnQuickSlot4;
                @QuickSlot5.started -= m_Wrapper.m_QuickSlotUIActionsCallbackInterface.OnQuickSlot5;
                @QuickSlot5.performed -= m_Wrapper.m_QuickSlotUIActionsCallbackInterface.OnQuickSlot5;
                @QuickSlot5.canceled -= m_Wrapper.m_QuickSlotUIActionsCallbackInterface.OnQuickSlot5;
                @QuickSlot6.started -= m_Wrapper.m_QuickSlotUIActionsCallbackInterface.OnQuickSlot6;
                @QuickSlot6.performed -= m_Wrapper.m_QuickSlotUIActionsCallbackInterface.OnQuickSlot6;
                @QuickSlot6.canceled -= m_Wrapper.m_QuickSlotUIActionsCallbackInterface.OnQuickSlot6;
            }
            m_Wrapper.m_QuickSlotUIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @QuickSlot1.started += instance.OnQuickSlot1;
                @QuickSlot1.performed += instance.OnQuickSlot1;
                @QuickSlot1.canceled += instance.OnQuickSlot1;
                @QuickSlot2.started += instance.OnQuickSlot2;
                @QuickSlot2.performed += instance.OnQuickSlot2;
                @QuickSlot2.canceled += instance.OnQuickSlot2;
                @QuickSlot3.started += instance.OnQuickSlot3;
                @QuickSlot3.performed += instance.OnQuickSlot3;
                @QuickSlot3.canceled += instance.OnQuickSlot3;
                @QuickSlot4.started += instance.OnQuickSlot4;
                @QuickSlot4.performed += instance.OnQuickSlot4;
                @QuickSlot4.canceled += instance.OnQuickSlot4;
                @QuickSlot5.started += instance.OnQuickSlot5;
                @QuickSlot5.performed += instance.OnQuickSlot5;
                @QuickSlot5.canceled += instance.OnQuickSlot5;
                @QuickSlot6.started += instance.OnQuickSlot6;
                @QuickSlot6.performed += instance.OnQuickSlot6;
                @QuickSlot6.canceled += instance.OnQuickSlot6;
            }
        }
    }
    public QuickSlotUIActions @QuickSlotUI => new QuickSlotUIActions(this);

    // MainMenuUI
    private readonly InputActionMap m_MainMenuUI;
    private IMainMenuUIActions m_MainMenuUIActionsCallbackInterface;
    private readonly InputAction m_MainMenuUI_StartMainMenu;
    public struct MainMenuUIActions
    {
        private @PlayerInput m_Wrapper;
        public MainMenuUIActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @StartMainMenu => m_Wrapper.m_MainMenuUI_StartMainMenu;
        public InputActionMap Get() { return m_Wrapper.m_MainMenuUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainMenuUIActions set) { return set.Get(); }
        public void SetCallbacks(IMainMenuUIActions instance)
        {
            if (m_Wrapper.m_MainMenuUIActionsCallbackInterface != null)
            {
                @StartMainMenu.started -= m_Wrapper.m_MainMenuUIActionsCallbackInterface.OnStartMainMenu;
                @StartMainMenu.performed -= m_Wrapper.m_MainMenuUIActionsCallbackInterface.OnStartMainMenu;
                @StartMainMenu.canceled -= m_Wrapper.m_MainMenuUIActionsCallbackInterface.OnStartMainMenu;
            }
            m_Wrapper.m_MainMenuUIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @StartMainMenu.started += instance.OnStartMainMenu;
                @StartMainMenu.performed += instance.OnStartMainMenu;
                @StartMainMenu.canceled += instance.OnStartMainMenu;
            }
        }
    }
    public MainMenuUIActions @MainMenuUI => new MainMenuUIActions(this);

    // Skill_Implement
    private readonly InputActionMap m_Skill_Implement;
    private ISkill_ImplementActions m_Skill_ImplementActionsCallbackInterface;
    private readonly InputAction m_Skill_Implement_FindingTarget;
    private readonly InputAction m_Skill_Implement_ClickTarget;
    public struct Skill_ImplementActions
    {
        private @PlayerInput m_Wrapper;
        public Skill_ImplementActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @FindingTarget => m_Wrapper.m_Skill_Implement_FindingTarget;
        public InputAction @ClickTarget => m_Wrapper.m_Skill_Implement_ClickTarget;
        public InputActionMap Get() { return m_Wrapper.m_Skill_Implement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Skill_ImplementActions set) { return set.Get(); }
        public void SetCallbacks(ISkill_ImplementActions instance)
        {
            if (m_Wrapper.m_Skill_ImplementActionsCallbackInterface != null)
            {
                @FindingTarget.started -= m_Wrapper.m_Skill_ImplementActionsCallbackInterface.OnFindingTarget;
                @FindingTarget.performed -= m_Wrapper.m_Skill_ImplementActionsCallbackInterface.OnFindingTarget;
                @FindingTarget.canceled -= m_Wrapper.m_Skill_ImplementActionsCallbackInterface.OnFindingTarget;
                @ClickTarget.started -= m_Wrapper.m_Skill_ImplementActionsCallbackInterface.OnClickTarget;
                @ClickTarget.performed -= m_Wrapper.m_Skill_ImplementActionsCallbackInterface.OnClickTarget;
                @ClickTarget.canceled -= m_Wrapper.m_Skill_ImplementActionsCallbackInterface.OnClickTarget;
            }
            m_Wrapper.m_Skill_ImplementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @FindingTarget.started += instance.OnFindingTarget;
                @FindingTarget.performed += instance.OnFindingTarget;
                @FindingTarget.canceled += instance.OnFindingTarget;
                @ClickTarget.started += instance.OnClickTarget;
                @ClickTarget.performed += instance.OnClickTarget;
                @ClickTarget.canceled += instance.OnClickTarget;
            }
        }
    }
    public Skill_ImplementActions @Skill_Implement => new Skill_ImplementActions(this);

    // LoadingUI
    private readonly InputActionMap m_LoadingUI;
    private ILoadingUIActions m_LoadingUIActionsCallbackInterface;
    private readonly InputAction m_LoadingUI_GoToNextScene;
    public struct LoadingUIActions
    {
        private @PlayerInput m_Wrapper;
        public LoadingUIActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @GoToNextScene => m_Wrapper.m_LoadingUI_GoToNextScene;
        public InputActionMap Get() { return m_Wrapper.m_LoadingUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LoadingUIActions set) { return set.Get(); }
        public void SetCallbacks(ILoadingUIActions instance)
        {
            if (m_Wrapper.m_LoadingUIActionsCallbackInterface != null)
            {
                @GoToNextScene.started -= m_Wrapper.m_LoadingUIActionsCallbackInterface.OnGoToNextScene;
                @GoToNextScene.performed -= m_Wrapper.m_LoadingUIActionsCallbackInterface.OnGoToNextScene;
                @GoToNextScene.canceled -= m_Wrapper.m_LoadingUIActionsCallbackInterface.OnGoToNextScene;
            }
            m_Wrapper.m_LoadingUIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @GoToNextScene.started += instance.OnGoToNextScene;
                @GoToNextScene.performed += instance.OnGoToNextScene;
                @GoToNextScene.canceled += instance.OnGoToNextScene;
            }
        }
    }
    public LoadingUIActions @LoadingUI => new LoadingUIActions(this);
    private int m_PlayerSchemeIndex = -1;
    public InputControlScheme PlayerScheme
    {
        get
        {
            if (m_PlayerSchemeIndex == -1) m_PlayerSchemeIndex = asset.FindControlSchemeIndex("Player");
            return asset.controlSchemes[m_PlayerSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnTempItemUse(InputAction.CallbackContext context);
        void OnTakeItem(InputAction.CallbackContext context);
        void OnTestMakeItem(InputAction.CallbackContext context);
    }
    public interface IInventoryUIActions
    {
        void OnInventoryOnOff(InputAction.CallbackContext context);
        void OnInventoryItemUse(InputAction.CallbackContext context);
    }
    public interface IStoreUIActions
    {
        void OnStoreUIOnOff(InputAction.CallbackContext context);
    }
    public interface IEquipmentUIActions
    {
        void OnEquipmentOnOff(InputAction.CallbackContext context);
        void OnEquipmentItemUse(InputAction.CallbackContext context);
    }
    public interface ISkillUIActions
    {
        void OnSkillWindowOnOff(InputAction.CallbackContext context);
    }
    public interface IQuickSlotUIActions
    {
        void OnQuickSlot1(InputAction.CallbackContext context);
        void OnQuickSlot2(InputAction.CallbackContext context);
        void OnQuickSlot3(InputAction.CallbackContext context);
        void OnQuickSlot4(InputAction.CallbackContext context);
        void OnQuickSlot5(InputAction.CallbackContext context);
        void OnQuickSlot6(InputAction.CallbackContext context);
    }
    public interface IMainMenuUIActions
    {
        void OnStartMainMenu(InputAction.CallbackContext context);
    }
    public interface ISkill_ImplementActions
    {
        void OnFindingTarget(InputAction.CallbackContext context);
        void OnClickTarget(InputAction.CallbackContext context);
    }
    public interface ILoadingUIActions
    {
        void OnGoToNextScene(InputAction.CallbackContext context);
    }
}
